#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n
case $n in
    1)
        echo "One";;         
    2|3|4|5|6|7|8|9)
        echo "Digit 2-9";;
    [1-9][0-9]) 
        echo "Two Digit 10-99";;
    [0-9][0-9][0-9])
        echo "Three Digit";;
    *.txt)
        echo "Four";;  
    *)
        echo "Other";;
esac
    